name: Build & Push

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "apps/renderer/package-lock.json"

      - name: Install dependencies
        working-directory: apps/renderer
        run: npm ci

      - name: Build
        working-directory: apps/renderer
        run: npm run build

      - name: Run unit tests
        working-directory: apps/renderer
        run: npm run test:run

      - name: Sync version with release tag
        working-directory: apps/renderer
        run: npm version $(echo ${GITHUB_REF##*/} | sed 's/^v//') --no-git-tag-version --allow-same-version

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        working-directory: apps/renderer
        run: npm publish --access public

      - name: Success notification
        run: echo "âœ… Package @gannochenko/staticstripes successfully published!"
